global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ghostworks-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # FastAPI application metrics
  - job_name: 'ghostworks-api'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # OpenTelemetry Collector metrics
  - job_name: 'otelcol'
    static_configs:
      - targets: ['otelcol:8889']
    scrape_interval: 15s
    metrics_path: /metrics

  # Nginx metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL metrics (if postgres_exporter is added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    metrics_path: /metrics

  # Celery Worker metrics
  - job_name: 'ghostworks-worker'
    static_configs:
      - targets: ['worker:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node.js application metrics (if prom-client is configured)
  - job_name: 'ghostworks-web'
    static_configs:
      - targets: ['web:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics