apiVersion: 1

policies:
  - orgId: 1
    receiver: default-receiver
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 10s
    group_interval: 10s
    repeat_interval: 1h
    routes:
      - receiver: critical-alerts
        matchers:
          - severity = critical
        group_wait: 5s
        group_interval: 5s
        repeat_interval: 30m
      - receiver: warning-alerts
        matchers:
          - severity = warning
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h